name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  dio: ^5.8.0+1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  build_runner: ^2.4.0
  retrofit_generator: ^8.0.0
  json_serializable: ^6.6.0
