include:
  - package:very_good_analysis/analysis_options.yaml
  - package:bloc_lint/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_types_on_closure_parameters: ignore
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    # Style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: false # Conflicts with strict-inference
    always_use_package_imports: false # Allow relative imports within package
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    avoid_positional_boolean_parameters: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    directives_ordering: true
    package_api_docs: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_expression_function_bodies: false
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_raw_strings: true
    use_super_parameters: true

    # Documentation rules
    public_member_api_docs: false # Disable requirement for public API docs
    package_prefixed_library_names: true
    lines_longer_than_80_chars: false # Modern screens can handle longer lines

    # Flutter specific
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true

    # Error prevention
    always_require_non_null_named_parameters: true
    avoid_catching_errors: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    empty_catches: true
    hash_and_equals: true
    invariant_booleans: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true

    # Performance
    avoid_function_literals_in_foreach_calls: true
    avoid_slow_async_io: true
