name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.7.1
  retrofit_generator: ^9.2.0
  mockito: ^5.4.4
  test: ^1.24.9
